{{- if .Values.configmapData }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kelbi-app.fullname" . }}
  labels:
    {{- include "kelbi-app.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configmapData.contents }}
  {{ $key }}: |-
{{ $value | nindent 4 }}
{{- end }}
{{- end }}
