apiVersion: v1
kind: Service
metadata:
  name: {{ include "kelbi-app.fullname" . }}
  labels:
    {{- include "kelbi-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ default .Values.service.port .Values.config.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kelbi-app.selectorLabels" . | nindent 4 }}
