{{- $ports := include "kelbi-app.ports" . -}}
{{- if $ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kelbi-app.fullname" . }}
  labels:
    {{- include "kelbi-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{ $ports | nindent 4 }}
  selector:
    {{- include "kelbi-app.selectorLabels" . | nindent 4 }}
{{- end }}
