{{- $httpPort := include "kelbi-app.httpPort" . | trim }}
{{- if $httpPort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kelbi-app.fullname" . }}
  labels:
    {{- include "kelbi-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ $httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kelbi-app.selectorLabels" . | nindent 4 }}
{{- end }}
