providers:
  kubernetesCRD:
    allowCrossNamespace: true
traefik:
  logs:
    general:
      level: DEBUG
    access:
      enabled: false
  ingressRoute:
    dashboard:
      enabled: true
      matchRule: Host(`traefik.arcamh.com`)
      entryPoints:
        - web
        - websecure
  api:
    dashboard: true
    insecure: true
  tlsStore:
    default: {}

