postgresql:
  nameOverride: kelbi-pg-dev
  auth:
    postgresPassword: "kelbi"
  primary:
    service:
      type: LoadBalancer
  backup:
    enabled: true 
    timeZone: "America/Sao_Paulo"
    storage:
      storageClass: "local-path"